import { useEffect, useState, useCallback } from "react"
import { BASE_URL } from "../../utils/apiPaths"
import { useAuth } from "../../context/AuthContext"
import {
  FileText,
  Download,
  Calendar,
  ArrowUpRight,
  ArrowDownRight,
  PieChart,
  History,
  TrendingUp,
  TrendingDown,
  Minus
} from "lucide-react"

const Reports = () => {
  const { token, user } = useAuth()
  const authToken = token || localStorage.getItem("token")

  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())

  const fetchReport = useCallback(async () => {
    setLoading(true)
    try {
      const res = await fetch(
        `${BASE_URL}/api/reports/monthly?month=${selectedMonth}&year=${selectedYear}&_=${Date.now()}`,
        {
          headers: { Authorization: `Bearer ${authToken}` },
        }
      )
      if (!res.ok) {
        throw new Error(`HTTP error! status: ${res.status}`);
      }
      const data = await res.json();
      setReport(data)
      setError(null)
    } catch (err) {
      console.error("Report fetch error:", err)
      setError("Failed to fetch report data. Please try again.")
    } finally {
      setLoading(false)
    }
  }, [selectedMonth, selectedYear, authToken])

  useEffect(() => {
    fetchReport()
  }, [fetchReport])

  const handlePrint = () => {
    // Small delay to ensure all React renders and animations are stable
    setTimeout(() => {
      window.print()
    }, 500)
  }

  const exportToCSV = () => {
    if (!report || !report.transactions.length) return

    // 1. Build Metadata Header
    const metadata = [
      ["MONTHLY FINANCIAL REPORT"],
      ["Generated By", "FinTrack"],
      ["Account Owner", user?.name || "N/A"],
      ["Account Email", user?.email || "N/A"],
      ["Reporting Period", `${new Date(selectedYear, selectedMonth - 1).toLocaleString('default', { month: 'long' })} ${selectedYear}`],
      ["Export Date", new Date().toLocaleString()],
      [""],
      ["FISCAL PERFORMANCE SUMMARY"],
      ["Total Income", `₹${report.income.toLocaleString()}`],
      ["Total Expenses", `₹${report.expense.toLocaleString()}`],
      ["Net Savings/Balance", `₹${report.balance.toLocaleString()}`],
      ["Volume", `${report.transactions.length} Transactions`],
      [""],
      ["DETAILED TRANSACTION LOG"]
    ]

    // 2. Build Transaction Table
    const headers = ["Date", "Title", "Category", "Type", "Amount", "Splits"]
    const rows = report.transactions.map(t => [
      new Date(t.date).toLocaleDateString(),
      `"${t.title || t.description || t.notes || t.name || t.text || t.label || t.memo || t.remarks || t.reason || "Untitled"}"`,
      t.category || "General",
      (t.type || "expense").toUpperCase(),
      t.amount || 0,
      `"${(t.splitDetails || []).map(s => `${s.name}: ₹${s.amount} (${s.status})`).join(" | ")}"`
    ])

    // 3. Combine and Export
    const csvContent = [
      ...metadata.map(m => m.join(",")),
      headers.join(","),
      ...rows.map(r => r.join(","))
    ].join("\n")

    const blob = new Blob(["\ufeff" + csvContent], { type: "text/csv;charset=utf-8;" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.href = url
    link.download = `FinTrack_Report_${selectedYear}_${selectedMonth}.csv`
    link.click()
    URL.revokeObjectURL(url)
  }

  const getComparison = (current, previous) => {
    if (!previous || previous === 0) return null
    const diff = ((current - previous) / previous) * 100
    return {
      value: Math.abs(diff).toFixed(1),
      isIncrease: diff > 0,
    }
  }

  if (loading && !report) return (
    <div className="flex flex-col items-center justify-center h-64 space-y-6">
      <div className="relative">
        <FileText className="text-indigo-500 animate-pulse" size={64} />
        <div className="absolute inset-0 bg-emerald-50 hidden rounded-full animate-pulse" />
      </div>
      <p className="text-stone-600 font-semibold uppercase tracking-wide text-[10px]">Preparing your report…</p>
    </div>
  )

  if (error) return (
    <div className="p-6 rounded-xl bg-rose-500/5 border border-rose-500/10 text-rose-700 text-center">
      <p className="font-bold">{error}</p>
      <button onClick={fetchReport} className="mt-6 px-8 py-3 rounded-lg bg-rose-500/10 hover:bg-rose-500/20 transition-all font-semibold uppercase tracking-wide text-xs">Try Again</button>
    </div>
  )

  const incomeComp = getComparison(report?.income, report?.previousMonth?.income)
  const expenseComp = getComparison(report?.expense, report?.previousMonth?.expense)

  return (
    <div className="feature-page max-w-7xl mx-auto space-y-6 animate-in fade-in zoom-in duration-700 reports-page">
      <style>{`
        @media print {
          .no-print { display: none !important; }

          /* Reset the page container for documents */
          .reports-page {
            padding: 20px !important;
            margin: 0 !important;
            background: white !important;
            color: black !important;
            display: block !important;
            overflow: visible !important;
            height: auto !important;
          }

          /* Strip all glassmorphism and fancy backgrounds */
          .reports-page div, .reports-page section, .reports-page main {
            background: white !important;
            backdrop-filter: none !important;
            -webkit-backdrop-filter: none !important;
            border-color: #ddd !important;
            box-shadow: none !important;
          }

          /* Ensure ALL text is black and visible */
          .reports-page * {
            color: black !important;
            opacity: 1 !important;
            visibility: visible !important;
            transform: none !important;
            animation: none !important;
          }

          /* Force containers to expand naturally */
          .print-scroll-reset, .overflow-x-auto, .max-w-7xl, .space-y-6 {
            overflow: visible !important;
            height: auto !important;
            display: block !important;
            padding: 0 !important;
            border: none !important;
            max-width: none !important;
            margin: 0 !important;
          }

          table {
            width: 100% !important;
            border-collapse: collapse !important;
            margin-top: 20px !important;
            page-break-inside: auto !important;
          }
          tr {
            page-break-inside: avoid !important;
            page-break-after: auto !important;
          }
          thead { display: table-header-group !important; }
          tfoot { display: table-footer-group !important; }

          th { border-bottom: 2px solid #000 !important; padding: 12px !important; text-align: left !important; }
          td { border-bottom: 1px solid #eee !important; padding: 12px !important; }

          .print-header { display: block !important; margin-bottom: 40px !important; border-bottom: 4px solid #000 !important; padding-bottom: 20px !important; }
          .print-footer { display: block !important; position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; border-top: 1px solid #eee; padding: 10px; }

          .efficiency-meter, .category-bar { border: 1px solid #000 !important; }
          .category-fill { background: #000 !important; }
        }
        @media screen {
          .print-header, .print-footer { display: none; }
        }
      `}</style>

      {/* Print Header */}
      <div className="print-header hidden">
        <div className="flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-semibold text-emerald-800 mb-2">FinTrack</h1>
            <p className="text-stone-500 font-bold uppercase tracking-wide text-sm">Monthly Financial Statement</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-gray-900">{user?.name || 'Financial Member'}</p>
            <p className="text-sm text-stone-500">{user?.email}</p>
            <p className="text-xs text-stone-600 mt-2 italic">Report Generated: {new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </div>

      {/* Print Footer */}
      <div className="print-footer hidden">
        FinTrack &bull; Confidential Financial Statement &bull; Generated: {new Date().toLocaleString()}
      </div>

      {/* Header & Filters */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 no-print">


        <div className="flex items-center gap-4 bg-white backdrop-blur-xl p-2 rounded-lg border border-stone-200 shadow-sm">
          <div className="flex items-center gap-2 px-4">
            <Calendar size={18} className="text-emerald-800" />
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(Number(e.target.value))}
              className="bg-transparent text-stone-800 font-bold focus:outline-none cursor-pointer text-sm py-1.5"
            >
              {Array.from({ length: 12 }, (_, i) => (
                <option key={i + 1} value={i + 1} className="bg-white">
                  {new Date(0, i).toLocaleString('default', { month: 'long' })}
                </option>
              ))}
            </select>
          </div>
          <div className="w-[1px] h-6 bg-white" />
          <select
            value={selectedYear}
            onChange={(e) => setSelectedYear(Number(e.target.value))}
            className="bg-transparent text-stone-800 font-bold focus:outline-none cursor-pointer px-4 text-sm py-1.5"
          >
            {[2024, 2025, 2026].map(year => (
              <option key={year} value={year} className="bg-white">{year}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Executive Summary Card */}
      <div className="p-6 rounded-xl bg-emerald-100 overflow-hidden shadow-sm shadow-indigo-500/20 relative group">
        <div className="absolute -right-20 -top-20 w-64 h-64 bg-white rounded-full hidden group-hover:scale-125 transition-transform duration-700" />
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-8">
          <div className="space-y-4 max-w-2xl">
            <h2 className="text-3xl font-semibold text-stone-800 leading-tight">Monthly summary: <br/> {new Date(selectedYear, selectedMonth - 1).toLocaleString('default', { month: 'long' })}</h2>
            <p className="text-emerald-800 font-medium opacity-90 leading-relaxed text-sm">
              During this period, you processed <strong>{report?.transactions.length}</strong> transactions with a net balance of <strong className={report?.balance >= 0 ? 'text-emerald-800' : 'text-rose-700'}>₹{report?.balance.toLocaleString()}</strong>.
              {report?.balance >= 0
                ? " You maintained a positive balance, which is a strong indicator of financial health. Consider moving savings to your Savings Goals."
                : " Your expenses exceeded your income this month. We recommend reviewing your top categories below to identify potential areas for optimization."}
            </p>
          </div>
          <div className="flex flex-col items-center md:items-end justify-center min-w-[200px]">
             <p className="text-[10px] text-emerald-800 uppercase font-semibold tracking-wide mb-2">Efficiency Rating</p>
             <div className="text-4xl font-semibold text-stone-800">{report?.income > 0 ? Math.round((report.balance / report.income) * 100) : 0}%</div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

        {/* Left: Summary Metrics */}
        <div className="lg:col-span-1 space-y-6">
          <div className="p-8 rounded-xl bg-white backdrop-blur-xl border border-stone-200 overflow-hidden relative group shadow-sm">
             <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-50 rounded-full hidden -mr-24 -mt-24 transition-all group-hover:bg-emerald-50" />

             <h3 className="text-sm font-semibold text-stone-800 mb-8 flex items-center gap-2 uppercase tracking-tight">
               <History size={18} className="text-emerald-800" />
               Performance Audit
             </h3>

             <div className="space-y-8">
               <div className="relative z-10">
                 <p className="text-[10px] text-stone-500 uppercase font-semibold tracking-wide mb-2">Aggregate Income</p>
                 <div className="flex items-end gap-3">
                   <p className="text-3xl font-semibold text-stone-800 tabular-nums tracking-tight">₹{report?.income.toLocaleString()}</p>
                   {incomeComp && (
                     <span className={`text-[11px] font-semibold flex items-center mb-1.5 px-2 py-0.5 rounded-lg ${incomeComp.isIncrease ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-500/10 text-rose-700'}`}>
                       {incomeComp.isIncrease ? <TrendingUp size={10} className="mr-1" /> : <TrendingDown size={10} className="mr-1" />}
                       {incomeComp.value}%
                     </span>
                   )}
                 </div>
               </div>

               <div className="relative z-10">
                 <p className="text-[10px] text-stone-500 uppercase font-semibold tracking-wide mb-2">Aggregate Expenses</p>
                 <div className="flex items-end gap-3">
                   <p className="text-3xl font-semibold text-stone-800 tabular-nums tracking-tight">₹{report?.expense.toLocaleString()}</p>
                   {expenseComp && (
                     <span className={`text-[11px] font-semibold flex items-center mb-1.5 px-2 py-0.5 rounded-lg ${expenseComp.isIncrease ? 'bg-rose-500/10 text-rose-700' : 'bg-emerald-50 text-emerald-800'}`}>
                       {expenseComp.isIncrease ? <TrendingUp size={10} className="mr-1" /> : <TrendingDown size={10} className="mr-1" />}
                       {expenseComp.value}%
                     </span>
                   )}
                 </div>
               </div>

               <div className={`p-6 rounded-xl border transition-all ${report?.balance >= 0 ? 'bg-emerald-50 border-emerald-200' : 'bg-rose-500/5 border-rose-500/10 shadow-rose-500/5 shadow-inner'}`}>
                 <p className="text-[10px] text-stone-500 uppercase font-semibold tracking-wide mb-2">Net Financial Flow</p>
                 <p className={`text-4xl font-semibold tabular-nums tracking-tight ${report?.balance >= 0 ? 'text-emerald-800' : 'text-rose-700'}`}>
                   ₹{report?.balance.toLocaleString()}
                 </p>
               </div>
             </div>
          </div>

          <div className="grid grid-cols-2 gap-4 no-print">
            <button
              onClick={exportToCSV}
              className="p-6 rounded-xl bg-white border border-stone-200 text-stone-800 font-semibold uppercase tracking-wide text-xs transition-all shadow-sm hover:bg-white flex flex-col items-center justify-center gap-3 active:scale-95"
            >
              <Download size={20} className="text-stone-600" />
              <span>CSV</span>
            </button>
            <button
              onClick={handlePrint}
              className="p-6 rounded-xl bg-emerald-100 text-stone-800 font-semibold uppercase tracking-wide text-xs transition-all shadow-sm shadow-indigo-500/20 hover:bg-emerald-100 flex flex-col items-center justify-center gap-3 active:scale-95 btn-primary"
            >
              <FileText size={20} />
              <span>PDF / Print</span>
            </button>
          </div>
        </div>

        {/* Right: Detailed Breakdown & Transactions */}
        <div className="lg:col-span-2 space-y-8">
          {/* Category Breakdown */}
          <div className="p-8 rounded-xl bg-white backdrop-blur-xl border border-stone-200">
            <h3 className="text-sm font-bold text-stone-800 mb-8 flex items-center gap-2">
              <PieChart size={18} className="text-emerald-800" />
              Categorized Spending
            </h3>

            {report?.breakdown.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {report.breakdown.map((item, idx) => {
                  const percentage = Math.round((item.amount / report.expense) * 100);
                  return (
                    <div key={idx} className="group p-4 rounded-xl bg-white border border-stone-200 hover:bg-white hover:border-stone-200 transition-all">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-4">
                          <div className="w-10 h-10 rounded-lg bg-white border border-stone-200 flex items-center justify-center text-emerald-800 font-bold no-print">
                            {item.category[0]}
                          </div>
                          <div>
                            <p className="font-bold text-stone-800">{item.category}</p>
                            <p className="text-xs text-stone-500">{percentage}% of total</p>
                          </div>
                        </div>
                        <div className="text-right">
                          <p className="font-bold text-stone-800 tabular-nums">₹{item.amount.toLocaleString()}</p>
                        </div>
                      </div>
                      <div className="w-full h-1.5 bg-white rounded-full overflow-hidden no-print">
                        <div
                          className="h-full bg-emerald-100 transition-all duration-1000"
                          style={{ width: `${percentage}%` }}
                        />
                      </div>
                      {/* Print-only category bar */}
                      <div className="hidden print:block category-bar">
                         <div className="category-fill" style={{ width: `${percentage}%` }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center text-center p-12">
                <Minus className="text-stone-500 mb-4" size={32} />
                <p className="text-stone-600">No expenses recorded</p>
              </div>
            )}
          </div>

          {/* Transaction List */}
          <div className="p-8 rounded-xl bg-white backdrop-blur-xl border border-stone-200 overflow-hidden print-scroll-reset">
            <h3 className="text-sm font-bold text-stone-800 mb-6 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <History size={18} className="text-emerald-800" />
                Monthly Transactions
              </div>
              <span className="text-xs text-stone-500 font-normal">{report?.transactions.length} records found</span>
            </h3>

            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-stone-200">
                    <th className="pb-4 text-xs font-bold text-stone-500 uppercase tracking-wide">Date</th>
                    <th className="pb-4 text-xs font-bold text-stone-500 uppercase tracking-wide">Title</th>
                    <th className="pb-4 text-xs font-bold text-stone-500 uppercase tracking-wide text-center">Type</th>
                    <th className="pb-4 text-xs font-bold text-stone-500 uppercase tracking-wide">Category</th>
                    <th className="pb-4 text-xs font-bold text-stone-500 uppercase tracking-wide text-right">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-stone-200">
                  {report?.transactions.map((t) => (
                    <tr key={t._id || t.id} className="group hover:bg-white transition-colors">
                      <td className="py-4 text-sm text-stone-600 font-medium">
                        {new Date(t.date).toLocaleDateString(undefined, { day: '2-digit', month: 'short' })}
                      </td>
                      <td className="py-4 text-sm font-medium">
                        <p className="text-stone-800 font-bold">{t.title || t.description || t.notes || t.name || t.text || t.label || t.memo || t.remarks || t.reason || 'Untitled Transaction'}</p>
                        {t.splitDetails?.length > 0 && (
                          <div className="mt-1 flex flex-wrap gap-1">
                            {t.splitDetails.map((split, sIdx) => (
                              <span key={sIdx} className="text-[10px] px-1.5 py-0.5 rounded-md bg-white text-stone-500 border border-stone-200">
                                {split.name}: ₹{split.amount} ({split.status})
                              </span>
                            ))}
                          </div>
                        )}
                      </td>
                      <td className="py-4 text-center">
                        <span className={`px-2 py-1 rounded-lg text-[10px] uppercase font-semibold ${t.type === 'income' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-500/10 text-rose-700'}`}>
                          {t.type}
                        </span>
                      </td>
                      <td className="py-4 text-sm text-stone-600">{t.category}</td>
                      <td className={`py-4 text-sm font-bold text-right tabular-nums ${t.type === 'income' ? 'text-emerald-800' : 'text-stone-800'}`}>
                        {t.type === 'income' ? '+' : '-'}₹{Math.abs(t.amount).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot className="border-t-2 border-stone-200">
                  <tr className="bg-white">
                    <td colSpan={4} className="py-6 px-4 text-xs font-semibold text-stone-600 uppercase tracking-wide text-right">Net Fiscal Flow</td>
                    <td className={`py-6 px-4 text-sm font-semibold text-right tabular-nums ${report?.balance >= 0 ? 'text-emerald-800' : 'text-rose-700'}`}>
                      ₹{report?.balance.toLocaleString()}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Reports
